-- 프로그래머스 SQL 고득점 Kit
-- SELECT 1번
SELECT 
    ANIMAL_ID, 
    ANIMAL_TYPE, 
    DATETIME, 
    INTAKE_CONDITION,
    NAME, 
    SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- SELECT 2번
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

-- SELECCT 3번
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick';

-- SElECT 4번
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged';

-- SELECT 5번
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- SELECT 6번
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;

-- SELECT 7번
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1; 