-- 프로그래머스 고득점 Kit
-- SUM, MAX, MIN 1번
SELECT MAX(DATETIME) AS DATETIME
FROM ANIMAL_INS;

-- SUM, MAX, MIN 2번
SELECT MIN(DATETIME) AS DATETIME
FROM ANIMAL_INS;

-- SUM, MAX, MIN 3번
SELECT COUNT(*) AS count
FROM ANIMAL_INS;

-- SUM, MAX, MIN 4번
SELECT COUNT(DISTINCT(NAME)) AS count
FROM ANIMAL_INS;