-- 프로그래머스 고득점 Kit
-- GROUP BY 1번
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- GROUP BY 2번
SELECT NAME, COUNT(NAME) AS count
FROM ANIMAL_INS
GROUP BY NAME
HAVING count >= 2
ORDER BY NAME;
-- GROUP BY에서 조건문은 HAVING으로 처리

-- GROUP BY 3번
SELECT HOUR(DATETIME) AS hour, COUNT(*) AS count
FROM ANIMAL_OUTS
GROUP BY hour
HAVING hour BETWEEN 9 AND 20
ORDER BY hour;
