-- 프로그래머스 SQL 고득점 Kit
-- ISNULL 1번 문제
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE ISNULL(NAME);

-- ISNULL 2번 문제
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

-- ISNULL 3번 문제
SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS